# Generated by Django 4.2.1 on 2023-05-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(default=None, max_length=255, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=255)),
                ('fichier_CV', models.FileField(default=None, max_length=255, upload_to='uploads/')),
                ('fichier_photo', models.ImageField(default=None, max_length=255, upload_to='media/')),
                ('lien_linkedln', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(choices=[('dg', 'Design Graphique'), ('pa', 'Production Audiovisuelle'), ('c3d', 'Conception 3D')], default='dg', max_length=255)),
                ('details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artyprod.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('date_debut', models.DateField(default=None)),
                ('date_fin', models.DateField(default=None)),
                ('acheve', models.BooleanField(default=False)),
                ('equipe', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='artyprod.equipe')),
                ('services', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artyprod.service')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='personnels',
            field=models.ManyToManyField(to='artyprod.personnel'),
        ),
    ]
