# Generated by Django 4.2.1 on 2023-05-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='personnels',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='projet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='artyprod.projet'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='equipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artyprod.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Design Graphique', 'Design Graphique'), ('Production Audiovisuelle', 'Production Audiovisuelle'), ('Conception 3D', 'Conception 3D')], default='dg', max_length=255),
        ),
    ]
