# Generated by Django 4.2.1 on 2023-05-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
