# Generated by Django 4.2.1 on 2023-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='photo',
            field=models.ImageField(default=None, max_length=255, upload_to='media/'),
        ),
    ]
