# Generated by Django 4.2.1 on 2023-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0007_projet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='acheve',
            field=models.CharField(choices=[('o', 'Achevé'), ('n', 'Non achevé')], default='n', max_length=255),
        ),
    ]
