# Generated by Django 4.2.1 on 2023-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0008_alter_projet_acheve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='acheve',
            field=models.CharField(choices=[('Achevé', 'oui'), ('Non achevé', 'non')], default='non', max_length=255),
        ),
    ]
