# Generated by Django 4.2.1 on 2023-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0009_alter_projet_acheve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Design Graphique', 'DG'), ('Production Audiovisuelle', 'PA'), ('Conception 3D', 'C3D')], default='dg', max_length=255),
        ),
    ]
