# Generated by Django 4.2.1 on 2023-05-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0010_alter_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
