# Generated by Django 4.2.1 on 2023-05-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0011_equipe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
